services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server-john
      - server-paul
      - server-george
    ports:
    - "3000:80"

  server-john:
    build: ./server
    expose:
      - "3000"
    environment:
      - NAME=John

  server-paul:
    build: ./server
    expose:
      - "3000"
    environment:
      - NAME=Paul

  server-george:
    build: ./server
    expose:
      - "3000"
    environment:
      - NAME=George